name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Cria o diretório dist antes de salvar o arquivo
      - name: Create output directory
        run: mkdir -p dist

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AndreRuperto
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: "#FFA500" # Laranja
          color_dots: "#1e90ff"  # Azul (opcional, ajuste se necessário)

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
