name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Cria o diretório dist antes de salvar o arquivo
      - name: Create output directory
        run: mkdir -p dist

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3.2.0
        with:
          github_user_name: AndreRuperto
          outputs: |
            github-dark.svg?palette=github-dark&color_snake=orange
            github-light.svg?palette=github-light&color_snake=orange
            custom.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
