name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate a random color
        id: random_color
        run: |
          python3 -c '
          import random
          colors = [
              "red", "blue", "green", "yellow", "pink", "purple", "orange", "brown", 
              "black", "white", "gray", "cyan", "magenta", "lime", "teal", "navy", 
              "maroon", "olive", "aqua", "indigo", "violet", "gold", "silver", 
              "beige", "turquoise", "tan", "coral", "salmon", "lavender", "peach", 
              "khaki", "crimson", "amber", "emerald", "ivory", "plum", "periwinkle", 
              "charcoal", "mint", "scarlet", "fuchsia", "cherry", "sapphire", 
              "azure", "orchid", "ruby", "amber", "moss", "sand", "cobalt", "rose"
          ]
          color_snake = random.choice(colors)
          '

      - name: Generate snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=orange
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?palette=github-dark&color_snake=orange
            dist/github-contribution-grid-snake-random.svg?palette=github-dark&color_snake=${{ steps.random_color.outputs.color_snake }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}